version: "3"
services:
  web:
    build: .
    ports:
      - "3001:3000"
    command: ./node_modules/.bin/nodemon
    volumes:
      - .:/data
    working_dir: /data
    environment:
      - NODE_ENV=development

